#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  server: #server
#    eviction-interval-timer-in-ms: 10000 #服务器间隔多少毫秒做定期的删除的操作
#    renewal-percent-threshold: 0.85 #续约百分比，如果超过85%的应用没有和你续约，那么eureka会开启保护服务，不会剔除任何一个应用
#  instance: #实例
#    instance-id: ${eureka.instance.hostname}${spring.application.name}${server.port}
#    hostname: localhost #主机名称，或服务ip
#    prefer-ip-address: true #以ip的形式显示具体的服务信息
#    lease-renewal-interval-in-seconds: 5 #服务实例的续约时间间隔，因为eureka-server即是服务端也是客户端，要给自己续约，时间要不超过设定的时间
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  server: #server
#  instance: #实例
#    instance-id: ${eureka.instance.hostname}${spring.application.name}${server.port}
#    hostname: localhost #主机名称，或服务ip
#    prefer-ip-address: true #以ip的形式显示具体的服务信息
#    lease-renewal-interval-in-seconds: 5 #服务实例的续约时间间隔，因为eureka-server即是服务端也是客户端，要给自己续约，时间要不超过设定的时间
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance: #实例
    instance-id: ${spring.application.name}:${server.port}
#    hostname:  #主机名称，或服务ip
    prefer-ip-address: true #以ip的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 5 #服务实例的续约时间间隔，因为eureka-server即是服务端也是客户端，要给自己续约，时间要不超过设定的时间
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
